apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: reactive-web-app
build:
  artifacts:
    - image: reactive-web-app
      jib:
        args:
          - -DskipTests
deploy:
  kustomize:
    paths:
      - kustomization/base
profiles:
  - name: userDefinedPortForward
    portForward:
      - resourceType: deployment
        resourceName: reactive-web-app
        port: 8080
        localPort: 9090
  - name: bazel
    build:
      artifacts:
        - image: reactive-web-app
          bazel:
            target: //:reactive-web-app.tar
  - name: custom
    build:
      artifacts:
        - image: reactive-web-app
          custom:
            buildCommand: sh build.sh
  - name: gcb
    build:
      artifacts:
        - image: reactive-web-app
          docker:
            cacheFrom:
              - reactive-web-app
      googleCloudBuild: { }
  - name: kustomizeProd
    build:
      artifacts:
        - image: reactive-web-app
          jib:
            args:
              - -DskipTests
    deploy:
      kustomize:
        paths:
          - kustomization/overlays/prod
  - name: kustomizeBase
    deploy:
      kustomize:
        paths:
          - kustomization/base
  - name: kustomizeDev
    deploy:
      kustomize:
        paths:
          - kustomization/overlays/dev
  - name: jibWithHelm
    build:
      artifacts:
        - image: gcr.io/basic-curve-316617/reactive-web-app-helm
          jib:
            args:
              - -DskipTests
    deploy:
      helm:
        releases:
          - name: reactive-web-app-helm
            chartPath: reactive-web-app-helm
            artifactOverrides:
              imageKey: gcr.io/basic-curve-316617/reactive-web-app-helm
            valuesFiles:
              - reactive-web-app-helm/values.yaml
            imageStrategy:
              helm: { }
  - name: kaniko
    build:
      artifacts:
        - image: reactive-web-app
          kaniko: { }
      cluster:
        pullSecretName: kaniko-secret
        pullSecretPath: /Users/ashish/Downloads/kaniko-secret.json
  - name: docker
    build:
      artifacts:
        - image: reactive-web-app
      local: { }
  - name: pack
    build:
      artifacts:
        - image: reactive-web-app
          buildpacks:
            builder: gcr.io/buildpacks/builder:v1
            env:
              - GOOGLE_RUNTIME_VERSION=16
